GET http://localhost:3000/cats

###

POST  http://localhost:3000/cats
Content-Type: application/json

{
  "name": "Kitty",
  "age": 2
}

###

GET http://localhost:3000/dogs

###

POST  http://localhost:3000/dogs
Content-Type: application/json